### ISSUE TITLE
object 'filter_genes_with_one_transcript' not found

### ISSUE THREAD

**Issue by mtneuhoff** [michael-nakai/isopod#1]
Hi Michael,

many thanks for isopod. 

I succesfully installed isopod.
I tried running run_everything() on the test data provided:
I get the following error message:

<img width="710" alt="grafik" src="https://github.com/michael-nakai/isopod/assets/82835720/a37f4ceb-4eeb-462a-93cc-7bd7b7613986">

Is the function 'filter_genes_with_one_transcript' maybe renamed or do you know what causes the error?

Many thanks in advance. 

Best,
Marie

**Comment by michael-nakai** [comment]
Hey Marie,

Sorry for the delay! I've gotten around to fixing quite a few bugs including this one, so try redownloading/reinstalling the package and try again. Let me know if it still doesn't work
